Repository NetApp/terraform-provider-netapp-ontap, pull requests merged in 2025-02, with the labels that each got.

#328 [Enhancement]: Add SVM `storage_limit` parameter
  CHANGELOG.md
  docs/data-sources/svm.md
  docs/data-sources/svms.md
  docs/resources/svm.md
  examples/resources/netapp-ontap_svm/resource.tf
  internal/interfaces/svm.go
  internal/interfaces/svm_test.go
  internal/provider/svm/svm_data_source.go
  internal/provider/svm/svm_resource.go
  internal/provider/svm/svm_resource_test.go
  internal/provider/svm/svms_data_source.go
Labels: enhancement

#332 [Enhancement]: Add interface `service_policy` parameter
  CHANGELOG.md
  docs/data-sources/networking_ip_interface.md
  docs/data-sources/networking_ip_interfaces.md
  docs/resources/network_ip_interface.md
  examples/resources/netapp-ontap_network_ip_interface/resource.tf
  internal/interfaces/networking_ip_interface.go
  internal/provider/networking/network_ip_interface_data_source.go
  internal/provider/networking/network_ip_interface_resource.go
  internal/provider/networking/network_ip_interface_resource_alias_test.go
  internal/provider/networking/network_ip_interface_resource_test.go
  internal/provider/networking/network_ip_interfaces_data_source.go
Labels: enhancement

#334 [New Resource]: Ethernet Port
  CHANGELOG.md
  docs/data-sources/networking_ethernet_port_data_source.md
  docs/data-sources/networking_ethernet_ports_data_source.md
  docs/resources/network_ethernet_port_resource.md
  examples/data-sources/netapp-ontap_port/data-source.tf
  examples/data-sources/netapp-ontap_port/provider.tf
  examples/data-sources/netapp-ontap_port/terraform.tfvars
  examples/data-sources/netapp-ontap_port/variables.tf
  examples/data-sources/netapp-ontap_ports/data-source.tf
  examples/data-sources/netapp-ontap_ports/provider.tf
  examples/data-sources/netapp-ontap_ports/terraform.tfvars
  examples/data-sources/netapp-ontap_ports/variables.tf
  examples/resources/netapp-ontap_port/provider.tf
  examples/resources/netapp-ontap_port/resource.tf
  examples/resources/netapp-ontap_port/terraform.tfvars
  examples/resources/netapp-ontap_port/variables.tf
  internal/interfaces/networking_ethernet_port.go
  internal/provider/networking/network_ethernet_port_data_source.go
  internal/provider/networking/network_ethernet_port_resource.go
  internal/provider/networking/network_ethernet_port_resource_test.go
  internal/provider/networking/network_ethernet_ports_data_source.go
  internal/provider/provider.go
Labels: New Data Source, New Resource

#346 [Enhancement]: Add SVM QoS Policy Activation
  CHANGELOG.md
  docs/resources/svm_qos_policy_activation_resource.md
  examples/resources/netapp-ontap_svm_qos_policy_activation/provider.tf
  examples/resources/netapp-ontap_svm_qos_policy_activation/resource.tf
  examples/resources/netapp-ontap_svm_qos_policy_activation/terraform.tfvars
  examples/resources/netapp-ontap_svm_qos_policy_activation/variables.tf
  internal/interfaces/svm.go
  internal/provider/networking/network_ethernet_port_resource_test.go
  internal/provider/networking/network_ip_interface_resource_alias_test.go
  internal/provider/networking/network_ip_interface_resource_test.go
  internal/provider/provider.go
  internal/provider/svm/svm_qos_policy_activation_resource.go
  internal/provider/svm/svm_qos_policy_activation_resource_test.go
Labels: New Resource

#395 352 netapp-ontap_cifs_service - update docs
  CHANGELOG.md
  docs/resources/cifs_service.md
Labels: documentation
